WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-26 12:44:08.460483: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-26 12:44:08.460735: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-26 12:44:08.478860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-26 12:44:08.479796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-26 12:44:08.480738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-26 12:44:08.481655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-26 12:44:08.505341: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.031ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-26 12:44:08.767661: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-26 12:44:13.452897: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 6s - loss: 0.5027 - accuracy: 0.8034 - auc: 0.5325 - precision: 0.2000 - recall: 0.0331 - balanced_accuracy: 0.5024 - val_loss: 0.4465 - val_accuracy: 0.8218 - val_auc: 0.6532 - val_precision: 1.0000 - val_recall: 0.0047 - val_balanced_accuracy: 0.5023
Epoch 2/10
37/37 - 0s - loss: 0.4789 - accuracy: 0.8101 - auc: 0.5936 - precision: 0.3434 - recall: 0.0673 - balanced_accuracy: 0.5204 - val_loss: 0.4235 - val_accuracy: 0.8361 - val_auc: 0.6981 - val_precision: 0.9500 - val_recall: 0.0896 - val_balanced_accuracy: 0.5400
Epoch 3/10
37/37 - 1s - loss: 0.4571 - accuracy: 0.8226 - auc: 0.6400 - precision: 0.5212 - recall: 0.1015 - balanced_accuracy: 0.5416 - val_loss: 0.4090 - val_accuracy: 0.8497 - val_auc: 0.7213 - val_precision: 0.9474 - val_recall: 0.1698 - val_balanced_accuracy: 0.5770
Epoch 4/10
37/37 - 0s - loss: 0.4423 - accuracy: 0.8247 - auc: 0.6685 - precision: 0.5427 - recall: 0.1275 - balanced_accuracy: 0.5526 - val_loss: 0.3994 - val_accuracy: 0.8505 - val_auc: 0.7326 - val_precision: 0.9070 - val_recall: 0.1840 - val_balanced_accuracy: 0.5829
Epoch 5/10
37/37 - 0s - loss: 0.4311 - accuracy: 0.8308 - auc: 0.6920 - precision: 0.6085 - recall: 0.1523 - balanced_accuracy: 0.5674 - val_loss: 0.3920 - val_accuracy: 0.8547 - val_auc: 0.7448 - val_precision: 0.9167 - val_recall: 0.2075 - val_balanced_accuracy: 0.5940
Epoch 6/10
37/37 - 0s - loss: 0.4177 - accuracy: 0.8420 - auc: 0.7107 - precision: 0.7089 - recall: 0.1983 - balanced_accuracy: 0.5899 - val_loss: 0.3856 - val_accuracy: 0.8573 - val_auc: 0.7552 - val_precision: 0.8909 - val_recall: 0.2311 - val_balanced_accuracy: 0.6109
Epoch 7/10
37/37 - 1s - loss: 0.4099 - accuracy: 0.8393 - auc: 0.7292 - precision: 0.6903 - recall: 0.1842 - balanced_accuracy: 0.5842 - val_loss: 0.3813 - val_accuracy: 0.8573 - val_auc: 0.7619 - val_precision: 0.8413 - val_recall: 0.2500 - val_balanced_accuracy: 0.6175
Epoch 8/10
37/37 - 0s - loss: 0.4004 - accuracy: 0.8456 - auc: 0.7436 - precision: 0.7320 - recall: 0.2161 - balanced_accuracy: 0.5997 - val_loss: 0.3776 - val_accuracy: 0.8598 - val_auc: 0.7676 - val_precision: 0.8286 - val_recall: 0.2736 - val_balanced_accuracy: 0.6350
Epoch 9/10
37/37 - 0s - loss: 0.3957 - accuracy: 0.8460 - auc: 0.7558 - precision: 0.7077 - recall: 0.2373 - balanced_accuracy: 0.6068 - val_loss: 0.3739 - val_accuracy: 0.8606 - val_auc: 0.7732 - val_precision: 0.8310 - val_recall: 0.2783 - val_balanced_accuracy: 0.6370
Epoch 10/10
37/37 - 1s - loss: 0.3938 - accuracy: 0.8484 - auc: 0.7570 - precision: 0.7035 - recall: 0.2633 - balanced_accuracy: 0.6186 - val_loss: 0.3708 - val_accuracy: 0.8657 - val_auc: 0.7779 - val_precision: 0.8732 - val_recall: 0.2925 - val_balanced_accuracy: 0.6459
Epoch 00010: val_loss improved from inf to 0.37078, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
INFO     Computation time for training the single-label model for AR: 0.21 min
WARNING  Using 4735 background data samples could cause slower run times. Consider using shap.sample(data, K) or shap.kmeans(data, K) to summarize the background as K samples.
  0%|                                                                                                                                    | 0/1184 [00:00<?, ?it/s]
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b7b14c1a820>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
  0%|                                                                                                                                    | 0/1184 [01:15<?, ?it/s]
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, x_test, model, target, opts.outputDir, drop_values=True, threshold=100, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 28, in shap_explain
    shap_values, indices = explainer.shap_values(x_test)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_kernel.py", line 190, in shap_values
    explanations.append(self.explain(data, **kwargs))
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_kernel.py", line 217, in explain
    self.varyingInds = self.varying_groups(instance.x)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_kernel.py", line 417, in varying_groups
    num_mismatches = np.sum(np.frompyfunc(self.not_equal, 2, 1)(x_group, self.data.data[:, inds]))
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_kernel.py", line 402, in not_equal
    return 0 if np.isclose(i, j, equal_nan=True) else 1
  File "<__array_function__ internals>", line 5, in isclose
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/numpy/core/numeric.py", line 2290, in isclose
    return within_tol(x, y, atol, rtol)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/numpy/core/numeric.py", line 2276, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/numpy/core/_ufunc_config.py", line 439, in __exit__
    seterr(**self.oldstate)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/numpy/core/_ufunc_config.py", line 111, in seterr
    old = geterr()
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/numpy/core/_ufunc_config.py", line 177, in geterr
    res['under'] = _errdict_rev[val]
KeyboardInterrupt