WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
2023-04-26 12:38:03.652043: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-26 12:38:03.652421: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-26 12:38:03.712212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-26 12:38:03.714331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-26 12:38:03.715994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-26 12:38:03.720064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-26 12:38:03.756234: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.058ms.
  function_optimizer: function_optimizer did nothing. time = 0.004ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-26 12:38:04.018280: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2023-04-26 12:38:08.989531: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 6s - loss: 0.5009 - accuracy: 0.7998 - auc: 0.5499 - precision: 0.2410 - recall: 0.0555 - balanced_accuracy: 0.5080 - val_loss: 0.4389 - val_accuracy: 0.8277 - val_auc: 0.6712 - val_precision: 1.0000 - val_recall: 0.0377 - val_balanced_accuracy: 0.5199
Epoch 2/10
37/37 - 1s - loss: 0.4715 - accuracy: 0.8173 - auc: 0.6049 - precision: 0.4430 - recall: 0.0826 - balanced_accuracy: 0.5304 - val_loss: 0.4206 - val_accuracy: 0.8345 - val_auc: 0.7207 - val_precision: 0.9444 - val_recall: 0.0802 - val_balanced_accuracy: 0.5393
Epoch 3/10
37/37 - 0s - loss: 0.4654 - accuracy: 0.8173 - auc: 0.6167 - precision: 0.4511 - recall: 0.0980 - balanced_accuracy: 0.5367 - val_loss: 0.4070 - val_accuracy: 0.8429 - val_auc: 0.7522 - val_precision: 0.9062 - val_recall: 0.1368 - val_balanced_accuracy: 0.5693
Epoch 4/10
37/37 - 0s - loss: 0.4475 - accuracy: 0.8279 - auc: 0.6570 - precision: 0.5769 - recall: 0.1417 - balanced_accuracy: 0.5602 - val_loss: 0.3970 - val_accuracy: 0.8429 - val_auc: 0.7693 - val_precision: 0.9062 - val_recall: 0.1368 - val_balanced_accuracy: 0.5693
Epoch 5/10
37/37 - 0s - loss: 0.4273 - accuracy: 0.8340 - auc: 0.6921 - precision: 0.6488 - recall: 0.1570 - balanced_accuracy: 0.5682 - val_loss: 0.3884 - val_accuracy: 0.8463 - val_auc: 0.7821 - val_precision: 0.8947 - val_recall: 0.1604 - val_balanced_accuracy: 0.5798
Epoch 6/10
37/37 - 1s - loss: 0.4222 - accuracy: 0.8363 - auc: 0.7054 - precision: 0.6488 - recall: 0.1854 - balanced_accuracy: 0.5814 - val_loss: 0.3813 - val_accuracy: 0.8429 - val_auc: 0.7921 - val_precision: 0.8095 - val_recall: 0.1604 - val_balanced_accuracy: 0.5761
Epoch 7/10
37/37 - 0s - loss: 0.4135 - accuracy: 0.8399 - auc: 0.7208 - precision: 0.6787 - recall: 0.1995 - balanced_accuracy: 0.5916 - val_loss: 0.3759 - val_accuracy: 0.8429 - val_auc: 0.7991 - val_precision: 0.7955 - val_recall: 0.1651 - val_balanced_accuracy: 0.5780
Epoch 8/10
37/37 - 0s - loss: 0.4058 - accuracy: 0.8433 - auc: 0.7336 - precision: 0.6996 - recall: 0.2172 - balanced_accuracy: 0.5969 - val_loss: 0.3710 - val_accuracy: 0.8463 - val_auc: 0.8048 - val_precision: 0.8125 - val_recall: 0.1840 - val_balanced_accuracy: 0.5863
Epoch 9/10
INFO     Computation time for training the single-label model for AR: 0.21 min
37/37 - 1s - loss: 0.4045 - accuracy: 0.8460 - auc: 0.7334 - precision: 0.7235 - recall: 0.2255 - balanced_accuracy: 0.6006 - val_loss: 0.3659 - val_accuracy: 0.8454 - val_auc: 0.8124 - val_precision: 0.7636 - val_recall: 0.1981 - val_balanced_accuracy: 0.5911
Epoch 10/10
37/37 - 0s - loss: 0.3907 - accuracy: 0.8486 - auc: 0.7607 - precision: 0.7152 - recall: 0.2550 - balanced_accuracy: 0.6164 - val_loss: 0.3621 - val_accuracy: 0.8446 - val_auc: 0.8165 - val_precision: 0.7414 - val_recall: 0.2028 - val_balanced_accuracy: 0.5927
Epoch 00010: val_loss improved from inf to 0.36211, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b10e39e5820>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
<class 'tuple'>	2
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, x_test, model, target, opts.outputDir, drop_values=True, threshold=100, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 27, in shap_explain
    explainer = shap.KernelExplainer(model, x_train[:x_train.shape:])
TypeError: slice indices must be integers or None or have an __index__ method